[package]
name              = "prices"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow       = { workspace = true }
chrono       = { workspace = true }
futures      = { workspace = true }
ledger-types = { workspace = true }
log          = { workspace = true }
rust_decimal = { workspace = true }
thiserror    = { workspace = true }
yfinance-rs  = { workspace = true }
