[package]
name              = "import"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow              = { workspace = true }
chrono              = { workspace = true }
clap                = { workspace = true }
csv                 = { workspace = true }
db                  = { workspace = true }
ledger              = { workspace = true }
ledger-types        = { workspace = true }
rust_decimal        = { workspace = true }
rust_decimal_macros = { workspace = true }
toml                = { workspace = true }

[dev-dependencies]
sqlx     = { workspace = true }
tempfile = { workspace = true }
tokio    = { workspace = true }
