[package]
name              = "store"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow              = { workspace = true }
chrono              = { workspace = true }
clap                = { workspace = true }
csv                 = { workspace = true }
db                  = { workspace = true }
ledger              = { workspace = true }
ledger-types        = { workspace = true }
log                 = { workspace = true }
portfolio           = { workspace = true }
prices              = { workspace = true }
rust_decimal        = { workspace = true }
rust_decimal_macros = { workspace = true }
serde               = { workspace = true }
sqlx                = { workspace = true }
strum               = { workspace = true }
strum_macros        = { workspace = true }
toml                = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio    = { workspace = true }
